# Site settings
baseurl = "https://bsidesatl.org/"
languageCode = "en-us"
title = "BSidesATL"
theme = "agency"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "bsidesatl"
  description = "Bsides Atlanta"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = true

  # Enable the BSidesATL Twitter Card image
  socialCard = true

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "BSidesATL"
    # Optional logo as brand stored in img/
    logo = "logo.svg"
    about = "About"
    speakers = "Speakers"
    #portfolio = "Portfolio"
    schedule = "Schedule"
    team = "Team"
    contact = "Contact"
    sponsors = "Sponsors"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "May 4 2019 - KSU Center, Kennesaw"
    subtitle = "BSides Atlanta"

    [[params.hero.links]]
      link = "https://goo.gl/forms/6EaIMdJqANC3ZSvm1"
      text = "Volunteer Signup"

    [[params.hero.links]]
      link = "https://ti.to/bsidesatl/bsidesatl2019/"
      text = "Tickets"

    # [[params.hero.links]]
    #   link = "bsidesatl.2018.cpe.form.pdf"
    #   text = "CPE Form"

    # [[params.hero.links]]
    #   link = "https://docs.google.com/forms/d/e/1FAIpQLScSveGPntHHofW_47WZkZbIEfrx4AxW-PtKshDlmaVHMbHWuA/viewform"
    #   text = "Attendee Survey"

  # About section
  [params.about]
    enable = true
    title = "About Security BSides"
    text = '''
Each BSides is a **community-driven** framework for building events for and by information security community members.  The goal is to expand the spectrum of conversation beyond the traditional confines of space and time.  It creates opportunities for individuals to both present and participate in an intimate atmosphere that encourages collaboration. It is an intense event with discussions, demos, and interaction from participants. It is where conversations for the next-big-thing are happening.

## CFP Dates

- Friday, February 1 - CFP opens
- Thursday, March 7 - CFP closes
- Friday, March 8 - CFP Review process begins
- Friday, March 29 - CFP Review process closes
- Monday, April 1 - CFP Decisions sent out


## Ticket Information

We're doing tickets a little differently this year. As always, BSides Atlanta 2019 is a free event that is open to all. This year we've added a Personal Sponsor option. This sponsorship helps pay for putting the conference on and gets you early access to a ticket.

We also decided to release free GA tickets in waves based on feedback from all of you. Check the schedule below and get your clicking fingers ready!

[Click here](https://ti.to/bsidesatl/bsidesatl2019) to get your tickets.

### Ticket Schedule

- Monday, February 18, Noon EST - Personal Sponsor tickets available
- Friday, March 1, Noon EST - Wave 1 of GA tickets available
- Monday, April 1, Noon EDT - Wave 2 of GA tickets available

A wait list will be available when Wave 2 completes. We will do our best to get tickets to as many people on the wait list as possible.
'''

    # About section
  [params.schedule]
    enable = true
    title = "Schedule"
    subtitle = "One day, endless entertainment"
    #endpoint = "Prepare<br>for<br>2019!"
    endpoint = "More<br>soon"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/schedule'.
    # Replace them with your own.
#    [[params.schedule.events]]
#      img = "bsides-square.png"
#      date = "9am"
#      title = "Doors open"
#      description = "Registration, CTFs, and Lockpick Village are open at this time."

    #[[params.schedule.events]]
    #  img = "bagels.jpg"
    #  date = "9am"
    #  title = "Bagels and Coffee in the lobby"
    #  description = "Provided by ?"

    [[params.schedule.events]]
      img = "speakers/dave.shackleford.jpg"
      date = ""
      title = "Keynote: Software-Defined Everything, and What That Means to Security"
      speaker = "Dave Shackleford"
      description = "What do security teams need to know about software-defined infrastructure, and new capabilities we may gain from using them ourselves? What will be some of the critical skill sets for security professionals now and in the future as these technologies become ever-more pervasive? In this presentation, Dave will cover everything from virtualization to containers, software-defined networking to public cloud, with a breakdown of key areas to focus on for security teams and specific advice for different security roles and positions."

  # Team section
  [params.speakers]
    enable = true
    # Possibility to center items
    #center = true
    title = "Our amazing speakers"
    subtitle = "Without them, we'd just be drinking coffee and eating lunch all day."
    #description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

    # All speakers member's pictures are stored under 'static/img/speakers'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.speakers.members]]
      img = "dave.shackleford.jpg"
      name = "Dave Shackleford"
      position = "Keynote: Software-Defined Everything, and What That Means to Security"
      company = "Voodoo Security"
      bio = """"""
      social = [
       ["fa-twitter", "https://twitter.com/daveshackleford"],
       ["fa-twitter", "https://twitter.com/voodoosecurity"],
      ]



  # Client section
    [params.sponsors_list]
      enable = true
      # Possibility to center items
      center = true
      # Optional sponsor title specifying the involvement
      title = "Our Sponsors"
      subtitle = "We thank these sponsors for making our event great!"

      # All the sponsors' logos are stored under 'static/img/logos'.
      # Replace them with your sponsors's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.sponsors.gold]]
        logo = "ksu-is.png"
        link = "http://coles.kennesaw.edu/information-systems/"
      [[params.sponsors.event]]
        logo = "foxpick.jpg"
        link = "https://twitter.com/Fox_Pick"
      [[params.sponsors.event]]
        logo = "cg-silvers.png"
        link = "https://www.cgsilvers.com/"
      [[params.sponsors.event]]
        logo = "netkoth.png"
        link = "https://netkoth.github.io"
      [[params.sponsors.event]]
        logo = "abe.png"
        link = "http://www.abesap.com"
      [[params.sponsors.silver]]
        logo = "coalfire.png"
        link = "https://www.coalfire.com/"
      [[params.sponsors.silver]]
        logo = "kudelskisecurity.png"
        link = "https://www.kudelskisecurity.com/"
      [[params.sponsors.inkind]]
        logo = "efga.png"
        link = "https://ef-georgia.org"

  # Footer section
  [params.footer]
    enable = true
    copyright = ""

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/bsidesatl"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/bsidesatl"
      title = "Github"


  [params.codeofconduct]
    enable = true
    title = "Code of Conduct"
    text = '''
**We have NO TOLERANCE for physical/verbal/sexual harassment of any human,
humanoid or AI!**

Our "Code of Conduct" is **"Be Excellent to Each Other"** AKA the Golden Rule.
Failing that, it is "Do not be an Ass* or we will kick your ass out!".

Asking questions of a speaker during their talk, to get clarity or debate a
point is NOT being an ass – heckling or haranguing the speaker IS. If you are
not sure, ask, or err on the side of basic decency and common courtesy. If what
they are doing would not be acceptable to have done to you, your best friend,
your worst enemy, your sister, niece, daughter, brother, nephew, son, mother,
father, or any human being, do not let them treat anyone else that way – whether
 you know them or not. **If someone asks you to stop – stop.**

**If you are having an issue with a BSidesATL participant of ANY type, find an
organizer.** They will assist you in determining the next steps for you to feel
safe and heard.

_*Staff reserves the right to determine what constitutes "Being an Ass"._
'''
